# -*- coding: utf-8 -*-
"""churn_DA_PRO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSdEhlwHBx4FbdM8JYzpCvJyhM9TSNQi

1. # import the database

# https://www.youtube.com/watch?v=tTtI2arH214
"""

from google.colab import files
uploaded = files.upload()

# importing the libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

conn = sqlite3.connect('customer_churn.db')

sql_query = """

  SELECT name
  FROM  sqlite_master
  WHERE type='table'
"""
tables= pd.read_sql(sql_query,conn)

# create database for each table

for table_name in tables['name']:
  df= pd.read_sql(f"SELECT * FROM {table_name}",conn)
  globals()[f"df_{table_name}"] = df
  print(f"Created dataframe : df{table_name}")
conn.close()

#print the tables name and column names just to check
conn = sqlite3.connect('customer_churn.db')

for table_name in tables['name']:
  print(f"\n Tables Name: {table_name}")
  #get column information
  column_query= f"PRAGMA table_info({table_name});"
  columns = pd.read_sql(column_query,conn)
  print("Columns: ")
  print(columns['name'].tolist())

#close connections
conn.close()

"""# 2. data cleaning"""

df_db_customer.head()

df_db_customer.info()

df_db_customer.tail()

# a. rename col - name
# b. drop columns - interest and pincode
# c. change data type  - dob
# d.  data standardization - gernder
# e. fix missing values -contry

# a. rename col - name

df_db_customer.rename(columns = {'name' : 'custmore_name'})

# b. drop columns - interest and pincode

# df_db_customer.drop(columns=['interest','pincode'])
df_db_customer.drop(df_db_customer.columns[-2:],axis=1)

#df_db_customer.columns[-2:]    # 6

# c. change data type - dob

df_db_customer['dob']=pd.to_datetime(df_db_customer['dob'])

df_db_customer['dob'].info()

# d. data standardization - gender

df_db_customer['gender'].unique()

df_db_customer['gender'] = df_db_customer['gender'].replace({'Men' : 'Male' , 'Women' : 'Female'})

# e. fix missing values - country

df_db_customer['country'].isna()
# true - values are there

df_db_customer[df_db_customer['country'].isna()]

state_country_mapping=df_db_customer.dropna(subset=['country']).set_index('state')['country'].to_dict()
# (0)

df_db_customer['country']=df_db_customer['country'].fillna(df_db_customer['state'].map(state_country_mapping))
#df_db_customer['country'].fillna(0)

df_db_customer[df_db_customer['country'].isna()]

"""new table subscription"""

df_db_subscription.head()

df_db_subscription.info()

date_col=['subscription_start_date','renewal_date','cancellation_date']

df_db_subscription[date_col] = df_db_subscription[date_col].apply(pd.to_datetime)

df_db_subscription.info()

"""new : customer support"""

df_db_support.head()

df_db_support.info()

# drop the last columns - col_1 , comment

df_db_support.drop(columns=['col_1','comment'],inplace=True, errors='ignore')

df_db_support['complaint_date'] = pd.to_datetime(df_db_support['complaint_date'])

df_db_support.info()

"""# 3. feature enginnering and data analysis"""

df_db_subscription['churn_flag'] = np.where(df_db_subscription['cancellation_date'].notna(),1,0)

df_db_subscription.head()

# 1st fix support table duplicates
df = (df_db_subscription
     .merge(df_db_customer, on= 'customerid', how= 'left')
     .merge(df_db_support, on= 'customerid', how= 'left'))

df.shape

df_db_subscription['customerid'].nunique()#net and clean row
#no duplicate row

df_db_customer['customerid'].nunique()

df_db_support['customerid'].nunique()

df_db_support['customerid'].size # row 9

df_db_support.head()

# group or some data are repating 2 times
df_db_support['complaint_count'] = df_db_support.groupby('customerid')['customerid'].transform('count')

df_db_support = df_db_support.sort_values('complaint_date').drop_duplicates('customerid', keep='last')

df_db_support['customerid'].size # after drop the duplicate

# final merge
df = (df_db_subscription
     .merge(df_db_customer, on= 'customerid', how= 'left')
     .merge(df_db_support, on= 'customerid', how= 'left'))

df.shape

df.to_csv('exported_chrun_data.csv',index=False)

"""# Data analysis

### 1. Chrun Rate
"""

# 1. Chrun Rate
df.columns

churn_rate = df['churn_flag'].mean()*100
print(f"Churn Rate : {churn_rate:.2f}%")

"""### 2. Retension rate"""

retention_rate = 100 - churn_rate
print(f"Retention Rate : {retention_rate:.2f}%")
# this are  remaining users

"""### 3. Churn by plane type"""

churn_by_plan = df.groupby('plan_type')['churn_flag'].mean()*100
print("Churn Rate by Plan Type:")
print(churn_by_plan)

# 4 a. churn by state
churn_by_state = df.groupby('state')['churn_flag'].mean()*100
print("Churn Rate by State:")
print(churn_by_state)

# 4 b. churn by subscription type
churn_by_subscription = df.groupby('subscription_type')['churn_flag'].mean()*100
print("Churn Rate by Subscription Type:")
print(churn_by_subscription)

# 4 sum of revenue

# it seems monthly_charges is the column most likely intended for calculating revenue.
total_revenue = df['monthly_charges'].sum()
print(f"Total Revenue: ${total_revenue:.2f}")

"""###5. ARPU - Avg Revenue per User"""

df.columns

arpu = df['monthly_charges'].mean()
print(f'ARPU : {arpu:.2f}')

"""### 6. Avg customer Tenure
count of days users has used our service : cancellation date else current date
"""

today = pd.Timestamp.today()
### not total only one

df['tenure_days'] = np.where(df['cancellation_date'].notna(),
                             (df['cancellation_date'] - df['subscription_start_date']).dt.days,
                             (today - df['subscription_start_date']).dt.days)
df.head()

# avg tenure days
avg_tenure_days = df['tenure_days'].mean()
print("Avg Tenture (Days) = ",round(avg_tenure_days))

df.columns

df.head(2)

# calculate customer age
current_date = pd.Timestamp.today()
df['customer_age'] = (current_date - df['dob']).dt.days // 365
print(df['customer_age'])

display(df[['customerid', 'dob', 'customer_age']].head())

# revenue at risk - revenue lost from churned users

revenue_at_risk =  df.loc[df['churn_flag']==1,'monthly_charges'].sum()
print(f"Revenue At Risk : {revenue_at_risk:.2f}")

# 8. Esclation Rate

df['escalations'] .unique()

escalation_rate = (df['escalations'] == 'Yes').mean()
print(f"Escalation Rate : {escalation_rate:.2%}")

"""### 9. Avg complaint per user"""

avg_complaints = df['complaint_count'].sum() / df['customerid'].nunique()
print("Avg Compliansts Per User =",round(avg_complaints,2))

"""### 10. Correaltion Esclation vs churn"""

df['escalations'] = np.where(df['escalations'] == 'Y',1,0) # encoding
# str to int

corr_df = df[['customerid','escalations','churn_flag']].dropna()
# The 'escalations' column in 'df' is already numeric (0 or 1) from cell YNhRBSOcQ8nu.
# The line below is no longer needed and caused the issue by converting all to 0.
# corr_df['escalations'] = np.where(corr_df['escalations'] == 'Y', 1, 0)

correlation = corr_df['escalations'].corr(corr_df['churn_flag'])
print(f"Correlation between Escalations and Churn: {correlation:.2f}")

# encoding string to int type
df['escalations'] = np.where(df['escalations'] =='Y',1,0)

df.head(3)

"""### 11. churn risk - create a column using existing col - churn risk -"""

df['churn_score'].head()
# indu. 17 to 50 mostly going to be out of applications

conditions = [
    (df['churn_score'] < 50),
    (df['churn_score'] >= 50) & (df['churn_score'] < 70),
    (df['churn_score'] >= 70)  ]

choices = ['low','medium','high']

df['churn_risk'] = np.select(conditions,choices,default='unknown')

df[['churn_risk','churn_score']].tail()

"""# Visualization using Matplotlib"""

df_visual= df.copy()

df_visual.columns

from matplotlib.lines import lineStyles
from matplotlib import colors
# 4.1 Monthly Churn Trend (Time series KPI)

df_visual['cancellation_month']=df_visual['cancellation_date'].dt.to_period('M')

churn_trend = df_visual[df_visual['churn_flag'] == 1].groupby('cancellation_month').size()

plt.figure(figsize=(8,4))
plt.plot(churn_trend.index.astype(str),churn_trend.values,color="green"
, marker='o',linestyle="dashed",linewidth=2 , markersize=12 )
plt.title("Monthly Churn Trend")
plt.xlabel("Month")
plt.ylabel("Churned Customers")
plt.grid(True)
plt.show()

# 4.2 churn by plane type
churn_by_plan = df_visual.groupby('plan_type')['churn_flag'].mean() * 100

plt.figure(figsize=(8,6))
colors=plt.cm.Set2(np.linspace(0,1,len(churn_by_plan)))
plt.bar(churn_by_plan.index, churn_by_plan.values, color=colors)
plt.title("Churn Rate by Plan Type")
plt.xlabel("Plan Type")
plt.ylabel("Churn Rate (%)")
plt.show()

# 4.3  churn by states
churn_by_plan = df_visual.groupby('state')['churn_flag'].mean() * 100

colors = plt.cm.Set2(np.linspace(0,1,len(churn_by_plan)))

plt.figure(figsize=(7,4))
plt.bar(churn_by_plan.index, churn_by_plan.values ,color=colors)
plt.title("Churn Rate by State")
plt.xlabel("State")
plt.ylabel("Churn Rate (%)")
plt.xticks(rotation=90)
plt.show()

"""# Visulaization using Seaborn"""

# ancoding - convert str to numeric so that we can find corr between features
df_visual.columns

df_visual[['plan_type','contract_type','churn_score',
       'churn_flag','churn_risk','escalations']].head()



import warnings
warnings.filterwarnings('ignore')

df_encoded = df_visual[['plan_type','contract_type','churn_score',
       'churn_flag','churn_risk','escalations']]

categorical_cols = ['plan_type','contract_type','churn_risk']

for col in categorical_cols:
  df_encoded[col] = df_encoded[col].astype('category').cat.codes
# incorrect method of encoding - as numbers are not assigned based based on priority

# Heatmap (Correaltion matrix)

sns.heatmap(df_encoded.corr(),annot=True)

df_visual['plan_type'].unique()

# correct method of encoding - as numbers are not assigned based based on priority
df_encoded = df_visual[['plan_type','contract_type','churn_score',
       'churn_flag','churn_risk','escalations']]

order_mapping = {
    'plan_type' : ['Basic','Standard','Premium' ],
    'contract_type' : ['Month-to-Month','Annual'],
    'churn_risk' : ['low','medium','high']
}

for col, order in order_mapping.items():
  df_encoded[col] = pd.Categorical(df_encoded[col].astype('category'),categories=order,ordered=True)

df_encoded.head(5)

# Heatmap (Correaltion matrix)

# Recreate df_encoded and convert categorical columns to numerical codes for correlation calculation
df_encoded = df_visual[['plan_type','contract_type','churn_score',
       'churn_flag','churn_risk','escalations']].copy() # Make a copy to avoid SettingWithCopyWarning

order_mapping = {
    'plan_type' : ['Basic','Standard','Premium' ],
    'contract_type' : ['Month-to-Month','Annual'],
    'churn_risk' : ['low','medium','high']
}

for col, order in order_mapping.items():
  # First, convert to ordered categorical type
  df_encoded[col] = pd.Categorical(df_encoded[col], categories=order, ordered=True)
  # Then, convert to numerical codes
  df_encoded[col] = df_encoded[col].cat.codes

sns.heatmap(df_encoded.corr(),annot=True)

"""### Pairplot"""

sns.pairplot(df_encoded) # diff diff pairs can be compared

# can find out the relationship between the data

"""# catplt/Facegrid plot"""

sns.catplot(data=df_visual,
            x='plan_type',
            y='monthly_charges',
            hue='gender', # colors
            col='churn_risk')

# multi - dim compare

"""# Pivot table"""

pd.pivot_table(data=df_visual,
               index='plan_type',
               values='churn_flag',
               aggfunc='mean')

df_visual.columns

pd.pivot_table(data=df_visual,
               index='plan_type',
               values=['monthly_charges','customerid','churn_flag'],
               aggfunc={
                   'monthly_charges' : 'sum',
                   'customerid' : 'nunique',
                   'churn_flag' : 'mean'
               })

"""# working with SQL in python (pandas)"""

# create df in sql

conn = sqlite3.connect('test_data.sqlite')

# table details
conn.execute("CREATE TABLE user (first_name TEXT, country TEXT, money INT)")

# commit and save
conn.commit()

# insert tha data

cursor = conn.cursor()

# write sql query to insert records in sql tabele
cursor.execute(
    """
    INSERT INTO user VALUES
    ('harry','IND',30),
    ('bhu','GER',40),
    ('ram','USA',50)
    """
)
conn.commit()
print("table created and data inserted.")

# check inserted data in table

conn =sqlite3.connect('test_data.sqlite')

query = """
SELECT * FROM user
"""
df_results = pd.read_sql(query,conn)

df_results.head()

# aggregation

query= """
    SELECT country,sum(money) as total_money
    FROM user
    GROUP BY country
"""
df_agg = pd.read_sql(query,conn)
df_agg.head()

conn.close() # always close the connections
# once the task is over

